### ISSUE TITLE
To-Do List for Yuriko-CS v1.0.0

### ISSUE THREAD

**Issue by luca28pet** [ItalianDevs4PM/Yuriko-CS#1]
To-Do list for Yuriko-CS 1.0.0 -- MCPE 0.14.0
- [x] Make the server visible by MCPE
- [ ] Better Packet Listener
- [ ] Remove debug code
- [ ] Implement YAML configurations
- [ ] Implement NBT
- [ ] Implement network packets
- [ ] Implement worlds
- [ ] Implement very basic world and nether generator
- [ ] Implement base blocks and items
- [x] Implement command system
- [ ] Implement default commands
- [x] Implement permission system
- [ ] Implement default permissions
- [ ] Implement plugin system
- [ ] Implement inventory
- [ ] Implement crafting
- [ ] Implement hunger and experience
- [ ] Implement base gameplay mechanics
- [ ] Implement redstone
- [ ] Implement advanced blocks and items
- [ ] Implement advanced gameplay mechanics
- [ ] Implement advanced and fancy world and nether generator
- [ ] Implement caves
- [ ] Implement exec flags

**Comment by larryTheCoder** [comment]
how about .jar plugin loader?

**Comment by NyaomiDEV** [comment]
@larryTheCoder There will not be a .jar plugin loader, sorry.

**Comment by Flavius12** [comment]
@larryTheCoder The main goal of this project is to create a **_very fast**_ and _fully-featured_ MCPE server software. Supported plugins will be probably pure dynamic libraries (.dll). This means that plugins **_won't**_ reduce the server software speed.
Plugin creation is very simple as the internal API we're writing. You'll need just to install MonoDevelop ide and learn the API.
What I want to say after this long talk is that Yuriko-CS will have a custom plugin format and a custom plugin API as other server software (like PocketMine, Bukkit, Spigot...) have

**Comment by larryTheCoder** [comment]
Just saying how to open .cs file?

**Comment by NyaomiDEV** [comment]
@larryTheCoder With MonoDevelop :)

**Comment by NikoZazza** [comment]
@AryToNeX Or with visual studio

**Comment by SantX27** [comment]
New commands are coming!
